spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
    name: accounts
  profiles:
    active: "default"  # Ensure this profile exists

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver  # Optional unless troubleshooting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # Adjust to "none" or "validate" for production
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related Default APIs!"

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true
  endpoint:
    shutdown:
      enabled: true

cloud:
  openfeign:
    circuitbreaker:
      enabled: true

resilience4jcircuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 2

info:
  app:
    name: "Accounts Service"
    version: "1.0.0"
    description: "EazyBytes Accounts Service"
    contact:
      email: "example@example.com"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

server:
  port: 8080

logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG
